### ISSUE TITLE
How to Receive Intent From Native Android Application

### ISSUE THREAD

**Issue by sconway** [darryncampbell/plugin-intent-api-exerciser#1]
Is it possible to use this library to receive an intent that is broadcasted from a native Android application? I am looking to launch a Cordova application from a native Android application, and pass an object to the Cordova application. At the moment, I am able to launch the Cordova application with the following java code:
```
 Intent launchIntent = getActivity().getPackageManager().getLaunchIntentForPackage("com.example.survey");
if (launchIntent != null) {

            final Intent intent = new Intent("didShow");

            Bundle b = new Bundle();
            b.putString( "userdata", "{ data: 'test'}" );
            intent.putExtras( b);

            Log.d("START", "starting cordova app");
            getActivity().startActivity(launchIntent, b);//null pointer check in case package name was not found

            Log.d("SEND", "sending intent to cordova app");
            getActivity().sendBroadcast(intent); 
}
```

This launches the Cordova application without any issues, but I am unable to see the test data when the Cordova app opens. The code in my Cordova application is as follows: 

```
document.addEventListener('deviceReady', function(){

            alert('ready');

            window.plugins.intentShim.onIntent(function (intent) {
                alert('Received Intent: ' + JSON.stringify(intent));
            });

});
```

The onIntent callback fires if I open the Cordova application after the initial launch, but the goal here is to open the Cordova app from a separate native Android application and supply it with an object/string/integer the first time that it opens. Please let me know if you need any more information on this, and thank you very much for your time.

**Comment by darryncampbell** [comment]
Hi, I think getIntent() will work for you.  The functionality was in the plugin but was not detailed in the readme.  I have just updated the readme (https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/README.md) please see the method near the bottom.  This is also in the plugin exerciser application here: https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L216

**Comment by sconway** [comment]
Yep, that did the trick. Hopefully this will help someone else down the line. Thanks a lot!
