### ISSUE TITLE
Doesn't run with latest cordova

### ISSUE THREAD

**Issue by melounek** [darryncampbell/plugin-intent-api-exerciser#3]
after cloning and running `cordova platform add android` i see error:
```
Plugin doesn't support this project's cordova-android version. cordova-android: 8.1.0, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android
```
and after that another one `Cannot find module 'cordova-common'`

The folder `/platforms/android` is created, but `cordova run android` is not working because of `Error: Cannot find module 'q'`

I'm on version cordova 9.0.0 and on macbook.

background: I wanted to run this example because I was couldn't get plugin [darryncampbell-cordova-plugin-intent ](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent) running - on sharing plain text from other app I still cannot see my app in the share menu - So I wanted to see working example.

**Comment by darryncampbell** [comment]
Hi, can you please try again with the master branch.  I just checked in a fix that works on my machine with Cordova 9.  Looks like Cordova changed the build system a while back to move from config.xml to package.json and I haven't updated this app for a while.

**Comment by melounek** [comment]
yep, now it works, thank you!
