### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by vandolphreyes** [darryncampbell/plugin-intent-api-exerciser#4]
Hello Sir, thank you for this. But it doesn't work on my side, after multiple attempts. Basically I'm doing is,  I try to share a product from online app like lazada, it doesn't show up on the share list. Thank you

**Comment by darryncampbell** [comment]
Hi, what Intent are you trying to send exactly?

**Comment by vandolphreyes** [comment]
Hi @darryncampbell , thank you for your response.
I'm trying to send a product URL from an app. I go to the app product page, then clicking share icon, but I can't see this app from the list. I want my cordova app to receive the URL of the product.

**Comment by darryncampbell** [comment]
It doesn't sound like this plugin will meet your needs....  You likely need the receiver registered in the AndroidManifest.xml but this plugin only supports dynamic broadcast receivers I am afraid.

**Comment by vandolphreyes** [comment]
I see. Thank you, I thought it was available for every mime type so I tried to use `*/*,` my bad.
